# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: lichy24/flask-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: "flask-app"

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  targetPort: 8080
  nodePort: 30080

dbService:
  port: 27017
  targetPort: 27017

deployment:
  port:
    - containerPort: 80
    - containerPort: 8080


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# This is Secret for stroing sensitive data more information can be found here: https://kubernetes.io/docs/concepts/configuration/secret/
secret:
  enabled: true
  # This is the type of secret more information can be found here: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
  type: Opaque
  # This is the data for the secret more information can be found here: https://kubernetes.io/docs/concepts/configuration/secret/#secret-data
  data: 
    mongodb-username: admin
    mongodb-password: password

database:
  databaseName: &dbname db
  collectionName: &collectionname app_logs


# This is for setting up a cronjob more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
cronjob:
  enabled: true
  schedule: "0 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  containers:
    - name: log-printer
      image:
        repository: busybox
        pullPolicy: IfNotPresent
        tag: "latest"
      command: ["/bin/sh", "-c", "date >> /data/flask-pv/log.txt"]
      volumeMounts:
        - name: logs-pv
          mountPath: /data/flask-pv  
    - name: mongo-cronjob
      image:
        repository: mongo
        pullPolicy: IfNotPresent
        tag: "6.0"
      env:
        - name: dbName
          value: *dbname
        - name: collectionName
          value: *collectionname
      commands:
        - /bin/sh
        - -c
        - |
          mongosh "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@{{ include "flask-package.fullname" . }}-db-service:27017/${dbName}?authSource=admin" --eval "db.getSiblingDB('${dbName}').getCollection('${collectionName}').insertOne({timestamp: new Date(), source:  'cronjob'})" && \
          mongodump --uri="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@{{ include "flask-package.fullname" . }}-db-service:27017/${dbName}?authSource=admin" --archive=/data/flask-pv/mongo_backup.archive.gz --gzip
      volumeMounts:
        - name: logs-pv
          mountPath: /data/flask-pv 
  volumes:
    - name: logs-pv
      persistentVolumeClaim:
        claimName: flask-pvc
  restartPolicy: OnFailure
  concurrencyPolicy: Forbid

dbStatefulSet:
  container:
    name: mongodb
    image: 
      repository: mongo
      pullPolicy: IfNotPresent
      tag: 6.0
    port: 27017
    volumeMounts:
      - name: db-data
        mountPath: /data/db
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: flask-pvc
  


# this is for setting up a configmap more information can be found here: https://kubernetes.io/docs/concepts/configuration/configmap/
configmap:
  enabled: true
  # This is the data for the configmap more information can be found here: https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-data
  data: # TODO redo the configmap data
    mongo_port: "27017"
    mongo_db: *dbname
    mongo_collection: *collectionname

# this is for setting up a persistent volume more information can be found here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
persistentvolume:
  enabled: true
  name: flask-pv
  storage: 3Gi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: manual
  hostPath: /data/flask-pv

# this is for setting up a persistent volume claim more information can be found here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
persistentvolumeclaim:
  enabled: true
  name: flask-pvc
  storage: 1Gi
  accessMode: ReadWriteMany

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

