{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-package.fullname" . }}-secret
  labels:
    {{- include "flask-package.labels" . | nindent 4 }}
type: {{ index .Values.secret "type" }}
data:
  mongodb-username: {{ index .Values.secret.data "mongodb-username" | b64enc}}
  mongodb-password: {{ index .Values.secret.data "mongodb-password" | b64enc}}
{{- end }}